name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-*"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    strategy:
      max-parallel: 5
      matrix:
        image:
          - almalinux_8_appstream_1.16
          - almalinux_8_appstream_1.18
          - almalinux_8_appstream_1.20
          - almalinux_8_appstream_1.22
          - almalinux_8_epel-modular_mainline
          - almalinux_9
          - almalinux_9_appstream_1.22
        arch:
          - amd64
          - arm64v8

    env:
      BUILD_IMAGE: ${{ matrix.image }}
      BUILD_HOSTNAME: ${{ matrix.image }}.github.integ.jp

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Build RPM
        run: |
          ./build -p ${{ matrix.arch }} $(echo ${BUILD_IMAGE} | sed 's/_/:/g')

      - name: Remove conflict files
        if: matrix.arch != 'amd64'
        run: |
          rm -f rpmbuild/SRPMS/*.rpm
          ls -al rpmbuild/SRPMS/

      - name: Upload Assets
        uses: AButler/upload-release-assets@3d6774fae0ed91407dc5ae29d576b166536d1777 # v3.0
        with:
          files: "rpmbuild/SRPMS/*.rpm;rpmbuild/RPMS/*/*.rpm"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
