name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  create-release:
    runs-on: ubuntu-22.04

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  release:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        image:
          - centos_7
          - almalinux_8_appstream_1.16
          - almalinux_8_appstream_1.18
          - almalinux_8_appstream_1.20
          - almalinux_8_appstream_1.22
          - almalinux_8_epel-modular_mainline
          - almalinux_9
          - almalinux_9_appstream_1.22
        arch:
          - amd64
          - arm64v8

    env:
      BUILD_IMAGE: ${{ matrix.image }}
      BUILD_HOSTNAME: ${{ matrix.image }}.github.integ.jp

    steps:
      - uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build RPM
        id: build_rpm
        run: |
          ./build -p ${{ matrix.arch }} $(echo ${BUILD_IMAGE} | sed 's/_/:/g')
          echo "##[set-output name=release-tag;]$(echo ${{ github.ref }} | sed -e 's|refs/tags/||g')"

      - name: Remove conflict files
        if: matrix.arch != 'amd64'
        run: |
          rm -f rpmbuild/SRPMS/*.rpm
          ls -al rpmbuild/SRPMS/

      - name: Upload Assets
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "rpmbuild/SRPMS/*.rpm;rpmbuild/RPMS/*/*.rpm"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.build_rpm.outputs.release-tag }}
