name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - centos_7
          - almalinux_8_appstream_1.16
          - almalinux_8_appstream_1.18
          - almalinux_8_appstream_1.20
          - almalinux_8_epel-modular_1.20
          - almalinux_8_epel-modular_mainline
          - almalinux_9_appstream_1.20

    env:
      BUILD_IMAGE: ${{ matrix.image }}
      BUILD_HOSTNAME: ${{ matrix.image }}.github.integ.jp

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build RPM
        id: build_rpm
        run: |
          ./build $(echo ${BUILD_IMAGE} | sed 's/_/:/g')
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.image }}
          path: rpmbuild/**/*.rpm

