name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      max-parallel: 20
      matrix:
        image:
          - almalinux_8_appstream_1.16
          - almalinux_8_appstream_1.18
          - almalinux_8_appstream_1.20
          - almalinux_8_appstream_1.22
          - almalinux_8_epel-modular_mainline
          - almalinux_9
          - almalinux_9_appstream_1.22
        arch:
          - linux/amd64
          - linux/arm64/v8

    env:
      BUILD_IMAGE: ${{ matrix.image }}
      BUILD_HOSTNAME: ${{ matrix.image }}.github.integ.jp

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Build RPM
        run: |
          ./build -p ${{ matrix.arch }} $(echo ${BUILD_IMAGE} | sed 's/_/:/g')

      - name: Normalize artifact name
        run: echo "ARTIFACT_NAME=$(echo ${{ matrix.image }}-${{ matrix.arch }} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: rpmbuild/**/*.rpm
